### ISSUE TITLE
issue defining the users settings

### ISSUE THREAD

**Issue by ascotell** [danielpatenaude/python_enlighten_api#1]
I am sorry to bother you but I am having issue adding my information to the configs section.  Below I am going to give you an example of how I have mine setup.  The error I am getting is, name: 'adam' is not defined

   "name": adam,
    "user_id": adam@gmail.com,
    "site_id": 2265555,
    "api_url": api.enphaseenergy.com/api/v2/systems,
    "api_key": c98a101222ff3487958ce5555555555,
    "spreadsheet_id": adam@gmail.com
    
    Any advise you have would be great.
    
    Thanks

**Comment by danielpatenaude** [comment]
Your json needs to be formatted with enclosing double quotes around the strings in order to be properly formatted json. E.g.:

```
configs = \
[{
    "name": "adam",
    "user_id": "adam@gmail.com",
    "site_id": "2265555",
    "api_url": "https://api.enphaseenergy.com/api/v2/systems",
    "api_key": "c98a101222ff3487958ce5555555555",
    "spreadsheet_id": "adam@gmail.com"
}]
```

That's not very obvious in my provided example, so I'll fix that.

**Comment by ascotell** [comment]
Thank you!  I will try this tomorrow.

**Comment by ascotell** [comment]
This fixes the issues
