### ISSUE TITLE
Error handling incorrect?

### ISSUE THREAD

**Issue by jaccol** [danielpatenaude/python_enlighten_api#10]
Hi Daniel,

If you make an error when connecting to enphase, the error is not displayed/logged right.

This line:
https://github.com/danielpatenaude/python_enlighten_api/blob/adc41d94cdb57f6ececd8f7f3356fddae2557533/utils/enlightenAPI_v4.py#L20
will result in `NameError: name 'dl' is not defined`

Maybe just replace `dl.error` with `print` ?

Jacco

**Comment by danielpatenaude** [comment]
Yeah that was a typo from when I used to use a logging library. I'll push that fix here shortly. Thanks!

**Comment by danielpatenaude** [comment]
Fixed! 
https://github.com/danielpatenaude/python_enlighten_api/commit/50145d3c2da9c46327b7f0feb2dbbd69ca346ef5
