### ISSUE TITLE
README Feedback

### ISSUE THREAD

**Issue by rjjkm** [danielpatenaude/python_enlighten_api#4]
I was experimenting with this project and encountered the same issue called out in the README:
_"It appears there's a new v4 route (/api/v4/systems/{System_id}/devices/micros/{serial_no}/telemetry) that can get microinverter data based on a date range. This seems the more ideal way to get daily inverter data than my current way of having to get the current lifetime data minus the stored value. But unfortunately I have not been able to successfully call this route using the Enlighten API v4 docs. So maybe this route doesn't do what I think it does, and their docs don't make it very clear what it does. I always get a 401 - Not Authorized. If someone is able to get that figured out, please feel free to let me know."_

I believe the issue (at least for me) stems from the free developer "Watt" plan which does not include device level monitoring. This is only included with the paid plans:
![image](https://user-images.githubusercontent.com/1816645/209989472-9e992521-30a6-4e6e-81ef-4d0064236702.png)

Unrelated, a few typos in the README:
_"The Enphase API lacks the ~~granulatiry~~ granularity of seeing per ~~inveter~~ inverter daily stats."_

Thank you for sharing this project.

**Comment by danielpatenaude** [comment]
Thanks for pointing that out. I'll update the readme for that and fix my spelling mistakes. I rushed to get the v4 API update out before the v2 API turned off and got a little sloppy. 😞
