### ISSUE TITLE
Subscription plan WATT -> api: /api/v4/systems/{system_id}/telemetry/production_micro

### ISSUE THREAD

**Issue by olikra** [danielpatenaude/python_enlighten_api#8]
Hi Daniel,

thanks for this repo. It's quite frustrating that enphase does not allow requesting on microinverter-level for subscription-plan watt. The enphase system (26 panels/inverters) will get installed in the next months, so I started to prepare some monitoring for the system including forecasting.

Have you ever tried the api: "/api/v4/systems/{system_id}/telemetry/production_micro" ? And what kind of data will you get?

Additional question: In which region/area is your system installed? Is 26,1 kW on 07.02.2022 the real production over all modules?

Thanks in advance.
olikr

**Comment by danielpatenaude** [comment]
@olikra I just tried that route on the free WATT plan and got the 401 error. Are you able to run that route on the free plan? Maybe I set it up wrong in Postman or something silly. 

Regarding your second question, I'm in the South East USA, and this was all live data from 2022 from when I made the public template.

**Comment by danielpatenaude** [comment]
@olikra It was a postman issue that I had. Here's the results of that route:

```
{
    "system_id": XXXXXXXX,
    "granularity": "day",
    "total_devices": 27,
    "start_at": 1691899200,
    "end_at": 1691912700,
    "items": "intervals",
    "intervals": [],
    "meta": {
        "status": "normal",
        "last_report_at": 1691952385,
        "last_energy_at": 1691912700,
        "operational_at": 1596827700
    }
}
```

It's being added in the PR https://github.com/danielpatenaude/python_enlighten_api/pull/9
